spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://1.117.167.241:3306/gulimall_ums?useSSL=false
mybatis-plus:
  #  *的意思是不仅是当前包路径下的mapper包扫描，而且所有的包都会去扫描
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000