server:
  port: 11000
spring:
  application:
    name: gulimall-ware
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gulimall?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
  jackson:
    date-format: yyyy-MM-dd:mm:ss
mybatis-plus:
  #  *的意思是不仅是当前包路径下的mapper包扫描，而且所有的包都会去扫描
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
